GET_FILENAME_COMPONENT(DLib_DIR "../DLib/build" ABSOLUTE)

FIND_LIBRARY(DLib_LIBRARY DLib PATHS ${DLib_DIR})

SET(DLib_LIBRARIES ${DLib_LIBRARY})
SET(DLib_LIBS ${DLib_LIBRARY})

GET_FILENAME_COMPONENT(DLib_INCLUDE_DIR "../DLib/include" ABSOLUTE)

SET(DLib_INCLUDE_DIRS ${DLib_INCLUDE_DIR})