GET_FILENAME_COMPONENT(DBoW2_DIR "../DBoW2/build" ABSOLUTE)

FIND_LIBRARY(DBoW2_LIBRARY DBoW2 PATHS ${DBoW2_DIR})

SET(DBoW2_LIBRARIES ${DBoW2_LIBRARY})
SET(DBoW2_LIBS ${DBoW2_LIBRARY})

GET_FILENAME_COMPONENT(DBoW2_INCLUDE_DIR "../DBoW2/include" ABSOLUTE)

SET(DBoW2_INCLUDE_DIRS ${DBoW2_INCLUDE_DIR})